# 输入图片文件夹路径
input: "InputImages"
# 输出文本文件夹路径
output: "TXTResults"

# OpenAI 相关配置
openai_base_url: "https://api.openai.com/v1" # OpenAI API 基础 URL (或兼容的代理)
openai_api_key: "YOUR-APIKey-Here" # 你的 OpenAI API 密钥
openai_model: "gpt-4o" # 要使用的 OpenAI 模型

# Google GenAI (Gemini) 相关配置
genai_api_key: "YourGenAIKeyHere" # 你的 Google GenAI API 密钥
genai_model: "gemini-2.0-flash" # 要使用的 GenAI 模型

# 批处理大小 (一次 API 调用处理的图片数量)
bind: 10
# 翻译目标语言 (例如 "简体中文", "English", 或留空不翻译)
translateTo: "简体中文"
# 选择使用的 AI 客户端 ('openai' 或 'genai')
clientType: "openai"
# 代理服务器地址 (例如 "http://127.0.0.1:9870" 或 "socks5://127.0.0.1:9870")
# 留空则使用系统代理设置
proxy: ""